apiVersion: v1
kind: Pod
metadata:
 name: webapp
 namespace: devproject
spec:
 containers:
 - name: webcon
   image: sudarshanlnx/2022sundayweb:v1
   imagePullPolicy: Always
   ports:
   - containerPort: 80
     name: apache
     protocol: TCP
   resources:
         requests:
           memory: "200Mi"
           cpu: "200m"
         limits:
           memory: "300Mi"
           cpu: "400m"
   env:
   - name: classname
     valueFrom:
       configMapKeyRef:
         name: test-config
         key: class.name
   - name: classday
     valueFrom:
       configMapKeyRef:
         name: test-config
         key: class.day
